### ISSUE TITLE
CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by Sosoyan** [vt-vl-lab/FGVC#17]
After generating a sequence of images, gif and the mp4 file I'm getting the following error on Centos 7. 

Any ideas?
> 
Traceback (most recent call last):
  File "video_completion.py", line 615, in <module>
    main(args)
  File "video_completion.py", line 578, in main
    video_completion_seamless(args)
  File "video_completion.py", line 558, in video_completion_seamless
    mask, video_comp = spatial_inpaint(deepfill, mask, video_comp)
  File "/home/megatron/FGVC/tool/spatial_inpaint.py", line 12, in spatial_inpaint
    img_res = deepfill.forward(video_comp[:, :, :, keyFrameInd] * 255., mask[:, :, keyFrameInd]) / 255.
  File "/home/megatron/FGVC/tool/frame_inpaint.py", line 35, in forward
    _, inpaint_res, _ = self.deepfill(image.to(self.device), mask.to(self.device), small_mask.to(self.device))
  File "/home/megatron/anaconda3/envs/FGVC/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/megatron/FGVC/models/DeepFill_Models/DeepFill.py", line 25, in forward
    stage1_output, resized_mask = self.stage_1(stage1_input, mask)
  File "/home/megatron/anaconda3/envs/FGVC/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/megatron/FGVC/models/DeepFill_Models/DeepFill.py", line 58, in forward
    x = self.down(x)
  File "/home/megatron/anaconda3/envs/FGVC/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/megatron/FGVC/models/DeepFill_Models/ops.py", line 116, in forward
    return self.out(x)
  File "/home/megatron/anaconda3/envs/FGVC/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/megatron/anaconda3/envs/FGVC/lib/python3.6/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/home/megatron/anaconda3/envs/FGVC/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/megatron/FGVC/models/DeepFill_Models/ops.py", line 52, in forward
    x = self.conv(x)
  File "/home/megatron/anaconda3/envs/FGVC/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/megatron/anaconda3/envs/FGVC/lib/python3.6/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/home/megatron/anaconda3/envs/FGVC/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/megatron/anaconda3/envs/FGVC/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDNN_STATUS_EXECUTION_FAILED
>

**Comment by gaochen315** [comment]
It seems like the image inpainting component (Deepfill) is the issue. Can you check your Pytorch and CUDA version? Are you using the `DFVI` environment?

**Comment by gaochen315** [comment]
Please check the latest code, which should be relatively easier to use. There is only one environment, i.e., Pytorch 1.6.0, CUDA 10.1. Let me know if you have any questions.

**Comment by gaochen315** [comment]
I’m closing this issue because it has been inactive for few months. Please reopen if you still encounter this issue.

Thank you!
