### ISSUE TITLE
Colab error

### ISSUE THREAD

**Issue by robbsaber** [vt-vl-lab/FGVC#39]
I get this error when running object removal on my own files : 

Calculating backward flow 69 <---> 70 
Finish flow prediction.
Traceback (most recent call last):
  File "video_completion.py", line 613, in <module>
    main(args)
  File "video_completion.py", line 576, in main
    video_completion_seamless(args)
  File "video_completion.py", line 464, in video_completion_seamless
    videoFlowF = complete_flow(args, corrFlowF, flow_mask, 'forward', FlowF_edge)
  File "video_completion.py", line 194, in complete_flow
    flow_mask_img = flow_mask[:, :, i] if mode == 'forward' else flow_mask[:, :, i + 1]
IndexError: index 16 is out of bounds for axis 2 with size 16

**Comment by boffyb** [comment]
I got a very similar error when I tried using a TIF sequence as the input, but it went away when I converted my sequence to PNGs
